
RENAME TABLE reply TO REPLY;
RENAME TABLE road TO ROAD;
RENAME TABLE road_comment TO ROAD_COMMENT;
RENAME TABLE subject TO SUBJECT;
RENAME TABLE comment TO COMMENT;
RENAME TABLE community TO COMMUNITY;
RENAME TABLE event TO EVENT;
RENAME TABLE marker TO MARKER;
RENAME TABLE member TO MEMBER;
RENAME TABLE notification TO NOTIFICATION;